spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

